name: check_temp
description: Check for temp comments like REMOVE, TEMP
version: 0.0.4
homepage: https://github.com/exaby73/check_temp

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  collection: ^1.16.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0

executables:
  check_temp: 
